services:
  - type: web
    name: projectml-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
